In [24]:
import pandas as pd
import numpy as np

In [25]:
#pd.set_option('display.max_rows',740)
file = pd.read_csv('case_time_series.csv')
file.drop(index=0,inplace=True)
file

Date    Date_YMD Daily Confirmed Total Confirmed  \
1    30 January 2020  2020-01-30               1               1   
2    31 January 2020  2020-01-31               0               1   
3    1 February 2020  2020-02-01               0               1   
4    2 February 2020  2020-02-02               1               2   
5    3 February 2020  2020-02-03               1               3   
..               ...         ...             ...             ...   
735  2 February 2022  2022-01-24          172846        41800963   
736  3 February 2022  2022-01-24          149574        41950537   
737  4 February 2022  2022-01-24          128121        42078658   
738  5 February 2022  2022-01-24          107493        42186151   
739  6 February 2022  2022-01-24           84972        42271123   

    Daily Recovered Total Recovered Daily Deceased Total Deceased  
1                 0               0              0              0  
2                 0               0              0              0  
3                 0               0              0              0  
4                 0               0              0              0  
5                 0               0              0              0  
..              ...             ...            ...            ...  
735          259083        39759560           1009         498443  
736          246668        40006228           1074         499517  
737          230792        40237020           1056         500573  
738          213220        40450240            868         501441  
739          199046        40649286            895         502336  

[739 rows x 8 columns]

In [26]:
file['Date_YMD'] = pd.to_datetime(file["Date_YMD"],format="%Y-%m-%d")
#file['Date_YMD']

In [27]:
filt = (file['Date_YMD'] >=pd.to_datetime('2021-05-01',format='%Y-%m-%d')) & (file['Date_YMD'] <=pd.to_datetime('2021-05-22',format='%Y-%m-%d'))
dataset_train =file.loc[filt]
dataset_train

Date   Date_YMD Daily Confirmed Total Confirmed Daily Recovered  \
458   1 May 2021 2021-05-01          392576        19549555          308688   
459   2 May 2021 2021-05-02          370090        19919645          300004   
460   3 May 2021 2021-05-03          355769        20275414          318910   
461   4 May 2021 2021-05-04          382847        20658261          337699   
462   5 May 2021 2021-05-05          412624        21070885          330718   
463   6 May 2021 2021-05-06          414280        21485165          328349   
464   7 May 2021 2021-05-07          406901        21892066          327675   
465   8 May 2021 2021-05-08          403808        22295874          386395   
466   9 May 2021 2021-05-09          366455        22662329          353777   
467  10 May 2021 2021-05-10          329491        22991820          355930   
468  11 May 2021 2021-05-11          348555        23340375          355398   
469  12 May 2021 2021-05-12          362632        23703007          352005   
470  13 May 2021 2021-05-13          343005        24046012          344676   
471  14 May 2021 2021-05-14          326256        24372268          353200   
472  15 May 2021 2021-05-15          310757        24683025          362547   
473  16 May 2021 2021-05-16          281837        24964862          378526   
474  17 May 2021 2021-05-17          263021        25227883          422391   
475  18 May 2021 2021-05-18          267246        25495129          389758   
476  19 May 2021 2021-05-19          276187        25771316          369005   
477  20 May 2021 2021-05-20          259242        26030558          357173   
478  21 May 2021 2021-05-21          257299        26287857          357625   
479  22 May 2021 2021-05-22          240897        26528754          355138   

    Total Recovered Daily Deceased Total Deceased  
458        15981706           3685         214933  
459        16281710           3423         218356  
460        16600620           3439         221795  
461        16938319           3786         225581  
462        17269037           3979         229560  
463        17597386           3923         233483  
464        17925061           4233         237716  
465        18311456           4092         241808  
466        18665233           3749         245557  
467        19021163           3879         249436  
468        19376561           4198         253634  
469        19728566           4128         257762  
470        20073242           4000         261762  
471        20426442           3889         265651  
472        20788989           4077         269728  
473        21167515           4098         273826  
474        21589906           4334         278160  
475        21979664           4529         282689  
476        22348669           3877         286566  
477        22705842           4209         290775  
478        23063467           4194         294969  
479        23418605           3739         298708

In [28]:
filt = (file['Date_YMD'] >=pd.to_datetime('23-05-2021',format='%d-%m-%Y')) & (file['Date_YMD'] <=pd.to_datetime('31-05-2021',format='%d-%m-%Y'))
dataset_test =file.loc[filt]
dataset_test

Date   Date_YMD Daily Confirmed Total Confirmed Daily Recovered  \
480  23 May 2021 2021-05-23          222834        26751588          302253   
481  24 May 2021 2021-05-24          195857        26947445          326737   
482  25 May 2021 2021-05-25          208992        27156437          295264   
483  26 May 2021 2021-05-26          211510        27367947          283054   
484  27 May 2021 2021-05-27          186075        27554022          271002   
485  28 May 2021 2021-05-28          174083        27728105          285332   
486  29 May 2021 2021-05-29          165282        27893387          264483   
487  30 May 2021 2021-05-30          153396        28046783          237664   
488  31 May 2021 2021-05-31          126883        28173666          255125   

    Total Recovered Daily Deceased Total Deceased  
480        23720858           4454         303162  
481        24047595           3509         306671  
482        24342859           4160         310831  
483        24625913           3843         314674  
484        24896915           3659         318333  
485        25182247           3611         321944  
486        25446730           3463         325407  
487        25684394           3130         328537  
488        25939519           2783         331320

In [29]:
m=22
# train death and days
days=np.arange(1,m+1)
daily_confirmed = dataset_train["Daily Confirmed"].to_numpy(dtype='float32')
daily_recovered = dataset_train["Daily Recovered"].to_numpy(dtype='float32')
deaths = np.abs(daily_recovered-daily_confirmed)
deaths,days

(array([ 83888.,  70086.,  36859.,  45148.,  81906.,  85931.,  79226.,
         17413.,  12678.,  26439.,   6843.,  10627.,   1671.,  26944.,
         51790.,  96689., 159370., 122512.,  92818.,  97931., 100326.,
        114241.], dtype=float32),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22]))

In [30]:
A=np.sum(days)
B=np.sum(deaths)
C=np.sum(days*days)
D=np.dot(deaths,np.transpose(days))

In [31]:
A,B,C,D

(253, 1421336.0, 3795, 18695149.0)

In [32]:
w0 = (B * C- A * D) / (m * C - A * A)
w0

34089.493506493505

In [33]:
w1 = (A * B - m * D) / (A * A - m * C)
w1

2653.6250705815924

In [34]:
test_days=np.arange(m+1,32)
test_deaths=np.abs(dataset_test['Daily Confirmed'].to_numpy(dtype='float32')-dataset_test['Daily Recovered'].to_numpy(dtype='float32'))
test_days,test_deaths

(array([23, 24, 25, 26, 27, 28, 29, 30, 31]),
 array([ 79419., 130880.,  86272.,  71544.,  84927., 111249.,  99201.,
         84268., 128242.], dtype=float32))

In [35]:
### error on test set
linear_error=0
for i in range(0,9):
    linear_error += (w0+w1*days[i]-test_deaths[i])**2
print("root-mean-square error",np.sqrt(linear_error/9))

root-mean-square error 53716.765808393306


In [36]:
# for 20April2021
d=-10
deaths1=w0+w1*d
print('predicted death',deaths1)
print('Actual death',np.abs(np.float32(file.loc[447,'Daily Confirmed'])-np.float32(file.loc[447,'Daily Recovered'])))

predicted death 7553.242800677581
Actual death 127709.0


In [37]:
# for 10june2020
d=41
deaths2=w0+w1*d
print('predicted death',deaths2)
print('Actual death',np.abs(np.float32(file.loc[498,'Daily Confirmed'])-np.float32(file.loc[498,'Daily Recovered'])))

predicted death 142888.1214003388
Actual death 43480.0


In [38]:
########### Quadratic model ########
#mat=numpy.concat(np.ones(m+1))
mat=np.stack((np.ones(m),days,days*days),axis=0)
mat = np.transpose(mat)
temp=np.dot(np.transpose(mat),mat)
temp1=np.dot(np.linalg.inv(temp),np.transpose(mat))
coff = np.dot(temp1,deaths)
w0=coff[0]
w1=coff[1]
w2=coff[2]
coff

array([ 93492.35064935, -12197.08921513,    645.68322981])

In [39]:
quadratic_error=0
for i in range(0,9):
    quadratic_error += (w0+w1*days[i]+w2*days[i]*days[i]-test_deaths[i])**2
print("root-mean-square error",np.sqrt(quadratic_error/9))

root-mean-square error 52162.38519623137


In [40]:
# for 20April2020
d=-10
deaths1=w0+w1*d+w2*d*d
print('predicted death',deaths1)
print('Actual death',np.abs(np.float32(file.loc[447,'Daily Confirmed'])-np.float32(file.loc[447,'Daily Recovered'])))

predicted death 280031.5657820443
Actual death 127709.0


In [41]:
# for 10june2020
d=41
deaths2=w0+w1*d+w2*d*d
print('predicted death',deaths2)
print('Actual death',np.abs(np.float32(file.loc[498,'Daily Confirmed'])-np.float32(file.loc[498,'Daily Recovered'])))

predicted death 678805.202145681
Actual death 43480.0
